PREFIX dblp: <https://dblp.org/rdf/schema#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX cito: <http://purl.org/spar/cito/>
SELECT ?this_publ ?other_publ WHERE {
  ?this_publ dblp:publishedIn ?this_venue .
  FILTER (?this_venue in ("PLDI", "ICFP", "OOPSLA", "POPL", "Proc. ACM Program. Lang."))
  ?this_publ dblp:omid ?this_omid .
  
  ?cite cito:hasCitingEntity ?this_omid .
  ?cite cito:hasCitedEntity ?other_omid .
  
  ?other_publ dblp:omid ?other_omid .
  ?other_publ dblp:publishedIn ?other_venue .
  FILTER (?other_venue in ("PLDI", "ICFP", "OOPSLA", "POPL", "Proc. ACM Program. Lang."))
  
}
